# Generated by Django 3.1.2 on 2020-10-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('id_minat', models.IntegerField()),
                ('student_class', models.IntegerField()),
                ('score_math', models.IntegerField()),
                ('score_science', models.IntegerField()),
                ('score_indonesian', models.IntegerField()),
                ('cluster', models.CharField(blank=True, default='', max_length=1)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
