# Generated by Django 3.1.2 on 2020-10-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Minat',
            new_name='Interest',
        ),
    ]
